Repository projectsyn/commodore-component-template, pull requests merged in 2023-01, with the labels that each got.

#37 Onboard vshn/component-appcat
  components.yaml
Labels: change

#40 Update kubent args for latest version of kubent
  {{ cookiecutter.slug }}/Makefile.vars.mk
Labels: bug

#39 Update PR checklist to clarify expectations
  .github/PULL_REQUEST_TEMPLATE.md
  {{ cookiecutter.slug }}/.github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement
