Repository projectsyn/commodore-component-template, pull requests merged in 2024-06, with the labels that each got.

#105 Onboard new components
  components.yaml
Labels: ignore

#106 Generate component `renovate.json` in post-gen-project hook
  README.md
  hooks/post_gen_project.py
  {{ cookiecutter.slug }}/renovate.json
Labels: change

#107 Allow customizing patch automerge behavior for selected dependencies
  cookiecutter.json
  hooks/post_gen_project.py
Labels: enhancement

#108 Allow enabling minor automerge based on patterns
  cookiecutter.json
  hooks/post_gen_project.py
Labels: enhancement

#110 Support for auto-releasing components
  cookiecutter.json
  hooks/post_gen_project.py
  {{ cookiecutter.slug }}/.github/workflows/auto-release.yaml
  {{ cookiecutter.slug }}/.github/workflows/release.yaml
Labels: enhancement
